version: '2'
name: nginx
services:
  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    networks:
      - mynetwork
    volumes:
      # - nginx-config:/etc/nginx
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
        mode: 0644

volumes:
  # nginx-config:
  letsencrypt:

networks:
  mynetwork:
    external: true

configs:
  nginx-config:
    file: ./default.conf